### PR TITLE
Add Python workloads

### PR DESCRIPTION
**Pull request by torsava**

### CODE REVIEW

**Comment by torsava** [comment]
Note that there's already a workload `sst_cs_apps-python-db-connectors.yaml` for PyMySQL and psychopg2, but we're not maintaining those, so it was added by Honza.

**Comment by torsava** [comment]
I recommend reviewing commit by commit, as I've sorted the list of unwanted python2 packages.

**Review by hroncok — APPROVED** [review]

**Comment by torsava** [comment]
Closing to reopen on upstream.

**Comment by torsava** [comment]
https://github.com/minimization/content-resolver-input/pull/68

**Pull request closed without merging**
